name: C/C++ CI

on: [push]

jobs:
  build:
    name: Windows build d3d12 arm
    runs-on: windows-11-arm
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: running python
      run: python3 -c "import platform; print(platform.machine())"